import Link from "next/link"

const sections = [
  {
    title: "1. The Service",
    content: (
      <>
        <p>
          [App Name] is a personal financial tracking application designed to
          help you record and organize income, expenses, transactions, and
          financial summaries.
        </p>
        <p>
          Features may include income and expense tracking, transaction
          categorization, financial summaries, reports, spending analysis, and
          account management.
        </p>
      </>
    ),
  },
  {
    title: "2. Not Financial Advice",
    content: (
      <>
        <p>
          [App Name] is a financial tracking and organization tool.
        </p>
        <p>
          Information, calculations, charts, summaries, and insights provided
          by the application are for informational and organizational purposes
          only. They are not financial, investment, tax, accounting, or legal
          advice.
        </p>
        <p>
          You are responsible for your own financial decisions and should
          consult a qualified professional when appropriate.
        </p>
      </>
    ),
  },
  {
    title: "3. Your Account",
    content: (
      <>
        <p>You are responsible for:</p>
        <ul>
          <li>Providing accurate account information.</li>
          <li>Keeping your login credentials secure.</li>
          <li>Maintaining the security of your account.</li>
          <li>Activity that occurs through your account.</li>
        </ul>
        <p>
          If you believe someone has accessed your account without permission,
          please contact us as soon as possible.
        </p>
      </>
    ),
  },
  {
    title: "4. Your Data",
    content: (
      <p>
        You retain ownership of the financial information and other content
        you enter into [App Name]. You grant us permission to store and process
        that information only as necessary to provide, maintain, secure, and
        improve the service, as described in our Privacy Policy.
      </p>
    ),
  },
  {
    title: "5. Acceptable Use",
    content: (
      <>
        <p>You agree not to:</p>
        <ul>
          <li>Use the service for unlawful purposes.</li>
          <li>Attempt to access another user's account.</li>
          <li>Interfere with or disrupt the service.</li>
          <li>Upload malicious code or harmful content.</li>
          <li>Attempt to bypass security features.</li>
          <li>Abuse or exploit the service.</li>
        </ul>
      </>
    ),
  },
  {
    title: "6. Accuracy of Information",
    content: (
      <p>
        We aim to provide reliable calculations and summaries, but we do not
        guarantee that the information generated by the service will always be
        completely accurate or error-free. You should verify important
        financial information before relying on it for financial, tax,
        accounting, or other significant decisions.
      </p>
    ),
  },
  {
    title: "7. Availability",
    content: (
      <p>
        We may modify, suspend, or discontinue parts of the service from time
        to time for maintenance, security, updates, operational reasons, or
        other circumstances. We will make reasonable efforts to keep the
        service available but do not guarantee uninterrupted access.
      </p>
    ),
  },
  {
    title: "8. Third-Party Services",
    content: (
      <p>
        The application may rely on third-party services for hosting,
        authentication, analytics, payments, email, storage, or other
        infrastructure. Your use of certain features may also be subject to
        the terms and policies of those third parties.
      </p>
    ),
  },
  {
    title: "9. Intellectual Property",
    content: (
      <p>
        The [App Name] application, including its design, branding, software,
        text, graphics, and original content, is owned by or licensed to us
        and protected by applicable intellectual property laws. These Terms do
        not transfer ownership of the application or its underlying technology
        to you.
      </p>
    ),
  },
  {
    title: "10. Account Termination",
    content: (
      <p>
        You may stop using [App Name] at any time. We may suspend or terminate
        an account if we reasonably believe that you have violated these
        Terms, abused the service, created a security risk, or used the service
        unlawfully.
      </p>
    ),
  },
  {
    title: "11. Disclaimer",
    content: (
      <p>
        To the maximum extent permitted by applicable law, [App Name] is
        provided on an "as is" and "as available" basis. We do not guarantee
        that the service will always be available, secure, accurate, or free
        from errors. Nothing in these Terms excludes or limits rights or
        protections that cannot legally be excluded or limited.
      </p>
    ),
  },
  {
    title: "12. Limitation of Liability",
    content: (
      <p>
        To the maximum extent permitted by applicable law, [App Name] and its
        operators will not be responsible for indirect, incidental, special,
        consequential, or similar losses arising from your use of the service,
        including losses resulting from reliance on financial summaries,
        calculations, or information generated by the application.
      </p>
    ),
  },
  {
    title: "13. Changes to These Terms",
    content: (
      <p>
        We may update these Terms from time to time. If we make material
        changes, we will take reasonable steps to notify users where
        appropriate. Your continued use of [App Name] after changes become
        effective means that you accept the updated Terms.
      </p>
    ),
  },
  {
    title: "14. Contact",
    content: (
      <p>
        If you have questions about these Terms, contact us at{" "}
        <a
          href="mailto:[Support Email]"
          className="font-medium text-foreground underline underline-offset-4"
        >
          [Support Email]
        </a>
        .
      </p>
    ),
  },
]

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-4xl px-6 py-12 md:px-8 md:py-20">
        {/* Header */}
        <div className="mb-12">
          <Link
            href="/"
            className="mb-8 inline-flex items-center text-sm text-muted-foreground transition-colors hover:text-foreground"
          >
            ← Back to dashboard
          </Link>

          <div className="mb-4 inline-flex rounded-full border border-border bg-muted px-3 py-1 text-xs font-medium text-muted-foreground">
            Legal
          </div>

          <h1 className="text-4xl font-semibold tracking-tight md:text-5xl">
            Terms of Service
          </h1>

          <p className="mt-4 text-sm text-muted-foreground">
            Last updated: September 7, 2026
          </p>

          <p className="mt-6 max-w-2xl text-base leading-7 text-muted-foreground">
            These terms explain the rules for using [App Name], a simple tool
            for tracking income, expenses, and personal financial summaries.
          </p>
        </div>

        {/* Content */}
        <div className="divide-y divide-border border-y border-border">
          {sections.map((section) => (
            <section key={section.title} className="py-8">
              <h2 className="text-lg font-semibold tracking-tight">
                {section.title}
              </h2>

              <div className="mt-4 space-y-4 text-sm leading-7 text-muted-foreground">
                {section.content}
              </div>
            </section>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-10 flex flex-col gap-4 border-t border-border pt-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between">
          <p>© 2026 [App Name]. All rights reserved.</p>

          <div className="flex gap-4">
            <Link
              href="/privacy"
              className="transition-colors hover:text-foreground"
            >
              Privacy Policy
            </Link>

            <Link
              href="/"
              className="transition-colors hover:text-foreground"
            >
              Home
            </Link>
          </div>
        </div>
      </div>
    </main>
  )
}
